# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        none

# Server
destination:      ./_site
exclude:          [".editorconfig", ".gitignore", "bower.json", "CNAME", "Gruntfile.js", "package.json", "node_modules", "README.md"]
port:             9001

# Custom vars
current_version:    3.2.0
